const { getDb } = require('../db');

/**
 * Creates a payout batch from pending earnings.
 * Ensures atomicity: all earnings updated OR none.
 * Uses BOTH cosmetic and dental DBs (per LOB v2).
 * @param {string[]} earningIds
 * @param {string} adminId
 * @param {string} cycleName
 * @returns {Promise<{ payout_id: string, updated_earnings_count: number }>} 
 */
async function createPayoutBatch(earningIds, adminId, cycleName) {
  // Use transaction across BOTH DBs
  const cosmeticDb = getDb('cosmetic');
  const dentalDb = getDb('dental');

  return await cosmeticDb.transaction(async (trx) => {
    // First, verify all earnings exist and are 'pending' in cosmetic DB
    const cosmeticEarnings = await trx('earnings')
      .whereIn('id', earningIds)
      .andWhere('status', 'pending');

    if (cosmeticEarnings.length !== earningIds.length) {
      throw new Error('Some earning IDs not found or not pending in cosmetic DB');
    }

    // Also verify in dental DB (for dual-write consistency)
    const dentalEarnings = await dentalDb('earnings')
      .whereIn('id', earningIds)
      .andWhere('status', 'pending');

    if (dentalEarnings.length !== earningIds.length) {
      throw new Error('Some earning IDs not found or not pending in dental DB');
    }

    // Insert payout record (id auto-generated by Postgres gen_random_uuid())
    const [{ id: payoutId }] = await trx('payouts').insert({
      admin_id: adminId,
      cycle_name: cycleName,
      status: 'processing',
    }).returning('id');

    // Update earnings in BOTH DBs
    await trx('earnings')
      .whereIn('id', earningIds)
      .update({ status: 'paid', payout_id: payoutId });

    await dentalDb('earnings')
      .whereIn('id', earningIds)
      .update({ status: 'paid', payout_id: payoutId });

    return {
      payout_id: payoutId,
      updated_earnings_count: earningIds.length,
    };
  });
}

module.exports = {
  createPayoutBatch,
};