// AUTO-GENERATED from product-map/contracts/permission-registry.yaml
// Do not edit manually. Run: npm run generate:permissions

module.exports.ALL_PERMISSIONS = [
  'appointments.add',
  'appointments.edit',
  'appointments.export',
  'appointments.view',
  'calendar.view',
  'commission.view',
  'customers.add',
  'customers.delete',
  'customers.edit',
  'customers.export',
  'customers.hard_delete',
  'customers.view',
  'customers.view_all',
  'employees.edit',
  'employees.view',
  'external_checkups.create',
  'external_checkups.upload',
  'external_checkups.view',
  'locations.edit',
  'locations.view',
  'notifications.view',
  'overview.view',
  'payment.add',
  'payment.edit',
  'payment.refund',
  'payment.view',
  'payment.void',
  'payments.export',
  'permissions.edit',
  'permissions.view',
  'products.export',
  'reports.export',
  'reports.view',
  'services.edit',
  'services.export',
  'services.view',
  'settings.edit',
  'settings.view',
  'website.edit',
  'website.view',
];

module.exports.PERMISSION_CATEGORIES = [
  'appointments',
  'calendar',
  'commission',
  'customers',
  'employees',
  'external_checkups',
  'locations',
  'notifications',
  'overview',
  'payment',
  'payments',
  'permissions',
  'products',
  'reports',
  'services',
  'settings',
  'website',
];
